"""empty message

Revision ID: f6f7cd2b87d9
Revises: 603bb74cb3ce
Create Date: 2024-06-08 22:00:03.871492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6f7cd2b87d9'
down_revision = '603bb74cb3ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('favorite_planet_id', sa.Integer(), nullable=True),
    sa.Column('favorite_people_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['favorite_people_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['favorite_planet_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    op.drop_table('favorites')
    # ### end Alembic commands ###
